// <auto-generated />
using System;
using APIRest_Terminales.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIRest_Terminales.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230905185458_createDataBase_20230905")]
    partial class createDataBase_20230905
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("APIRest_Terminales.Models.Estado", b =>
                {
                    b.Property<int>("Id_estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_estado"), 1L, 1);

                    b.Property<string>("Estado_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_estado");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("APIRest_Terminales.Models.Fabricantes", b =>
                {
                    b.Property<int>("Id_fab")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_fab"), 1L, 1);

                    b.Property<string>("Fab_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fab_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_fab");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("APIRest_Terminales.Models.Terminales", b =>
                {
                    b.Property<int>("Id_terminal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_terminal"), 1L, 1);

                    b.Property<DateTime>("Fecha_estado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_fabricacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_estado")
                        .HasColumnType("int");

                    b.Property<int>("Id_fab")
                        .HasColumnType("int");

                    b.Property<string>("Terminal_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terminal_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_terminal");

                    b.HasIndex("Id_estado");

                    b.HasIndex("Id_fab");

                    b.ToTable("Terminales");
                });

            modelBuilder.Entity("APIRest_Terminales.Models.Terminales", b =>
                {
                    b.HasOne("APIRest_Terminales.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("Id_estado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIRest_Terminales.Models.Fabricantes", "Fabricantes")
                        .WithMany()
                        .HasForeignKey("Id_fab")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Fabricantes");
                });
#pragma warning restore 612, 618
        }
    }
}
